language:
  - python

sudo:
  - required

python:
  - 2.7

node_js:
  - 0.10

install:
  - pip install -r .travis/requirements.txt --allow-unverified packagename
  - bash .travis/install-node.sh

script:
  - python unix-helpers/github-parser.py
  - node unix-helpers/push.js
