version: 1.0.{build}

branches:
  only:
    - main

build_script:
  - ps: 'powershell-helpers/generate.ps1'

artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\*.nuspec'
    name: nuspec

