version: 1.0.{build}

build_script:
  - ps: |
      if ($env:APPVEYOR_PULL_REQUEST_NUMBER -or $env:APPVEYOR_REPO_BRANCH -ne 'main') {
        & 'powershell-helpers\validate.ps1'
      } else {
        & 'powershell-helpers\generate.ps1'
      }

artifacts:
  - path: '**\*.nupkg'
    name: nupkg
  - path: '**\*.nuspec'
    name: nuspec
